### PR TITLE
make it support node >= 0.11 and iojs

### PR DESCRIPTION
**Pull request by XadillaX**
You can use it under node >= 0.11 and iojs now!

### CODE REVIEW

**Comment by XadillaX** [comment]
will this PR be accepted?

**Comment by justinethier** [comment]
Yes and thanks for your contribution. I just need to find some time to test it out, sorry for the delay.

**Comment by justinethier** [comment]
Done - this is being released as version 0.1.0. Thanks again!

**Comment by XadillaX** [comment]
You're welcome. Thanks for your project that ran in our projects!

**Pull request merged**
